# Generated by Django 5.0.3 on 2024-04-24 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatresponse',
            name='session_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatresponse',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
