# Generated by Django 5.0.3 on 2024-05-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0002_alter_defaultprompt_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultprompt',
            name='human_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
