# Generated by Django 5.0.3 on 2024-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0002_chatresponse_session_id_chatresponse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.CharField(choices=[('1', 'English'), ('2', 'Hindi'), ('3', 'Mathematics'), ('4', 'Science'), ('5', 'Social Science')], max_length=100, null=True),
        ),
    ]
