# Generated by Django 5.0.3 on 2024-04-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0003_document_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subject',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('mathematics', 'Mathematics'), ('science', 'Science'), ('social_science', 'Social Science')], max_length=100, null=True),
        ),
    ]
