# Generated by Django 5.0.3 on 2024-05-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0003_alter_defaultprompt_human_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='subjects/'),
        ),
    ]
