# Generated by Django 5.0.3 on 2024-05-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0004_subject_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='subjects/'),
        ),
    ]
