# Generated by Django 5.0.3 on 2024-04-29 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0004_alter_document_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='prompt',
            field=models.TextField(null=True),
        ),
    ]
