# Generated by Django 5.0.3 on 2024-04-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0006_defaultprompt_remove_document_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatresponse',
            name='subject',
            field=models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi'), ('mathematics', 'Mathematics'), ('science', 'Science'), ('social_science', 'Social Science')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='defaultprompt',
            name='human_prompt',
            field=models.TextField(null=True),
        ),
    ]
