# Generated by Django 5.0.3 on 2024-05-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llmware_api', '0007_chatresponse_subject_defaultprompt_human_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
